default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_42320_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_42320_test

production:
  <<: *default
  adapter: mysql2
  url: <%= ENV['DATABASE_URL'] %>
